apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default # Adjust this to your desired namespace
data:
  default.conf: |
    upstream microone {
        server microone:9001;
    }

    upstream microtwo {
        server microtwo:9002;
    }

    upstream microthree {
        server microthree:9003;
    }

    server {
        listen 80;
        server_name localhost;

        location /microone/ {
            rewrite ^/microone/(.*)$ /$1 break;
            proxy_pass http://microone;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /microtwo/ {
            rewrite ^/microtwo/(.*)$ /$1 break;
            proxy_pass http://microtwo;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /microthree/ {
            rewrite ^/microthree/(.*)$ /$1 break;
            proxy_pass http://microthree;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
